project:
  name: csoa
  regions:
    - us-east-1
tests:
  static:
    parameters:
      GitHubToken: '{{resolve:secretsmanager:github/personal-access-token:SecretString}}'
      SiteBucketName: delete-pmd-static-1533
    template: ./samples/static/pipeline.yml
