version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  build:
    commands:
      - echo In buildspec-setup.yml Build started on `date`
      - 'aws s3 mb s3://deoa-$(aws secretsmanager get-random-password --password-length 4 --exclude-numbers --exclude-punctuation --exclude-uppercase --output text)'
  post_build:
    commands:
      - echo In buildspec-setup.yml Build completed on `date`
artifacts:
  files:
    - '**/*'
