version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  build:
    commands:
      - echo In buildspec-setup.yml Build started on `date`
      - 'UUID=$(aws secretsmanager get-random-password --password-length 8 --exclude-numbers --exclude-punctuation --exclude-uppercase --output text)'
      - 'aws s3 mb s3://deoa-s3-$UUID'
      - 'aws s3 sync . s3://deoa-s3-$UUID'
      - cd samples/static
      - cd samples/ec2
      - zip deoa-ec2-examples.zip *.*
      - 'aws s3 sync . s3://deoa-s3-$UUID'
  post_build:
    commands:
      - echo In buildspec-setup.yml Build completed on `date`
artifacts:
  files:
    - '**/*'
